import { v4 as uuidv4 } from 'uuid';
export const allTags = [
  { id: uuidv4(), name: "bills" },
  { id: uuidv4(), name: "charity" },
  { id: uuidv4(), name: "drinks" },
  { id: uuidv4(), name: "education" },
  { id: uuidv4(), name: "extras" },
  { id: uuidv4(), name: "food" },
  { id: uuidv4(), name: "fitness" },
  { id: uuidv4(), name: "groceries" },
  { id: uuidv4(), name: "gifts" },
  { id: uuidv4(), name: "hobby" },
  { id: uuidv4(), name: "hotels" },
  { id: uuidv4(), name: "income" },
  { id: uuidv4(), name: "insurance" },
  { id: uuidv4(), name: "internet" },
  { id: uuidv4(), name: "investment" },
  { id: uuidv4(), name: "medicine" },
  { id: uuidv4(), name: "miscellaneous" },
  { id: uuidv4(), name: "others" },
  { id: uuidv4(), name: "ott" },
  { id: uuidv4(), name: "phone" },
  { id: uuidv4(), name: "rent" },
  { id: uuidv4(), name: "sports" },
  { id: uuidv4(), name: "stationary" },
  { id: uuidv4(), name: "subscription" },
  { id: uuidv4(), name: "shopping" },
  { id: uuidv4(), name: "travelling" },
  { id: uuidv4(), name: "transfer" },
  { id: uuidv4(), name: "wellness" },
];